### PR TITLE
Make HLL gob-serializable

### PR DESCRIPTION
**Pull request by sasha-s**
made everything but Hasher gob-serializable.

### CODE REVIEW

**Comment by mynameisfiber** [comment]
This looks great! Could you change the `travis.yml` to use more recent go versions (maybe 1.5, 1.4 and 1.3) and see if it passes the test?

**Comment by sasha-s** [comment]
Please have a another look.

**Comment by mynameisfiber** [comment]
Perfect! Any last changes before a merge?

**Comment by sasha-s** [comment]
I think it is good to go. Thanks!

**Pull request merged**
